(TeX-add-style-hook "Presentacion"
 (lambda ()
    (LaTeX-add-environments
     "definicion"
     "ejem"
     "defi"
     "ejer"
     "prop"
     "lema"
     "teor"
     "coro"
     "Boxedminipage")
    (LaTeX-add-labels
     "eq:dinError"
     "eq:4"
     "eq:accionNum"
     "eq:Lyapunov")
    (TeX-add-symbols
     '("PD" 2)
     "Rset"
     "Cset")
    (TeX-run-style-hooks
     "tabularx"
     "fancybox"
     "floatflt"
     "color"
     "graphicx"
     "multicol"
     "babel"
     "spanish"
     "geometry"
     "times"
     "cmbright"
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "bbm"
     "amsthm"
     "amssymb"
     "amsmath"
     "array"
     ""
     "latex2e"
     "beamer10"
     "beamer"
     "xcolor=svgnames"
     "Imgs/robotin"
     "Imgs/Coord_error")))

