
%Script del grafico de comparacion de los metodos eficientes vs optimizados

%vector de ns
X1=[10 30 100 300 1000 3000 10000];

%matriz de tiempos obtenidos para los métodos de Jacobi y 
%Gauss Seidel en sus formas eficientes y por componentes

Y1=[0.0156 0.0062 0.0422 0.3111 3.1743 27.5255 605.7931];           %J-C
Y2=[0.0112 5.2129e-04 7.8805e-04 0.0024 0.0113 0.0591 0.5418];      %GS-C
Y3=[0.0065 0.0070 0.0094 0.0329 2.2780 44.2363 1.0e+03 * 1.0242];   %J-E
Y4=[0.0058 0.0056 0.0067 0.0217 0.2455 2.3139 57.1905];             %GS-E

Y = [Y1 ; Y2 ; Y3 ; Y4];

%CREATEFIGURE(X1, Y)
%  X1:  vector of x data
%  Y:  matrix of y data

%  Auto-generated by MATLAB on 05-Oct-2016 15:22:22

% Create figure
figure1 = figure('Color',...
    [0.831372559070587 0.815686285495758 0.7843137383461]);

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,Y,'Parent',axes1);
set(loglog1(1),'Marker','^','LineStyle','--','Color',[0 0 1],...
    'DisplayName','Jacobi por componentes');
set(loglog1(2),'Marker','diamond','LineStyle','--','Color',[1 0 0],...
    'DisplayName','Gauss-Seidel por componentes');
set(loglog1(3),'Marker','^','Color',[1 0 1],...
    'DisplayName','Jacobi eficiente');
set(loglog1(4),'Marker','diamond','DisplayName','Gauss-Seidel eficiente',...
    'Color',[0 0 0]);

% Create title
title('Tiempo de Resolucion vs Tamaño de Matriz','FontWeight','bold',...
    'FontSize',11);

% Create xlabel
xlabel('n','FontWeight','bold','FontSize',11);

% Create ylabel
ylabel('t','FontWeight','bold','FontSize',11);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.180467091295117 0.633511938823285 0.382165605095541 0.193969030154849],...
    'Color',[1 0.949019610881805 0.866666674613953]);

